CREATE TABLE folders(
    id  VARCHAR(65535) PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE notes(
    id VARCHAR(65535)PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    modified TIMESTAMP DEFAULT now()NOT NULL,
    folderid VARCHAR(65535) REFERENCES folders(id) ON DELETE CASCADE NOT NULL,
    content TEXT NOT NULL
);